version: '3'
services:
  back-end:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
     - "5000:5000"
  front-end:
    build:
        context: .
        dockerfile: Dockerfile-frontend
    ports:
      - "8080:8080"